---
enable: false
schematicList:
  schematic:
    island:
      FILE_NAME: "island.schematic"
      NAME: "Island"
      DESCRIPTION: ""
      PERMISSION: "is.create"
      RATING: 1.8
      BIOME: "Plains"
      DEFAULT_PRIORITY: true