---
enable: true
schematicList:
  schematic:
    island:
      FILE_NAME: "island.schematic"
      NAME: "&aThe Original"
      DESCRIPTION: "The default island for starters. Great resource with extreme height."
      PERMISSION: "is.create"
      RATING: 1.8
      BIOME: "Plains"
      DEFAULT_PRIORITY: true