name: "SkyBlock"
version: "${pom.version}"
api: ["1.0.0"]
main: suomicraftpe.ASkyBlock
load: POSTWORLD
author: "Adam Matthew, Nukkit Coders, PetteriM1"
depend:
  - DbLib
softdepend:
  - EconomyAPI

permissions:
    is.create:
     default: true
     description: "Create an island"
    is.command:
     default: true
     description: "SkyBlock main command"
    is.command.teamChat:
     default: op
     description: "Enable chatting with team"
    is.command.message:
     default: true
     description: "Read the offline messages"
    is.command.expel:
     default: true
     description: "Kick a player from your island"
    is.command.leave:
     default: true
     description: "Leave island"
    is.command.lang:
     default: true
     description: "Set your default language"
    is.command.setspawn:
     default: op
     description: "Set the island main spawn."
    is.command.reset:
     default: true
     description: "Reset player island"
    is.command.home:
     default: true
     description: "Teleport back to home"
    is.command.info:
     default: true
     description: "get the players island info"
    is.command.teleport:
     default: true
     description: "Teleport to other island!"
    is.command.accept:
     default: true
     description: "accept an invitation"
    is.command.reject:
     default: true
     description: "Reject an invitation"
    is.command.edit:
     default: true
     description: "Edit your island information"
    is.command.invite:
     default: true
     description: "Invite a player"
    is.command.setworld:
     default: true
     description: "Set the player default world (Where island were generated)"
    is.panel.setting:
     default: true
     description: "A Setting panel for your island"
    is.mod.bypassprotect:
     default: op
     description: "Bypass the island Guard settings"
    is.mod.bypasslock:
     default: op
     description: "Bypass the island Lock settings"
    is.craft.enderchest:
     default: op
     description: "Bypass the enderchest usage"
    is.bypass.wait:
     default: op
     description: "Bypass the reset timer"
    is.admin.delete:
     default: op
     description: "Admin delete island command"
    is.admin.command:
     default: op
     description: "Admin main command"
    is.admin.generate:
     default: op
     description: "Generate a new island world"
    is.admin.kick:
     default: op
     description: "Kick a player from island world"
    is.admin.rename:
     default: op
     description: "Rename other players island"
    is.admin.setspawn:
     default: op
     description: "Set the world island location"
    is.admin.delete:
     default: op
     desctiption: "Delete an island"
